[package]
name = "server"
version = "0.1.0"
authors = ["Patrick OConnor <pjo2110@columbia.edu>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
